fastlane_require "dotenv"

before_all do
  Dotenv.load ".env.secret"
end

desc "Create on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Signing - manual mapping"
  lane :sign_mapping do
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end


  desc "Build binary - ad-hoc"
  lane :build_adhoc do
    sync_code_signing(type: "adhoc") # match
    sign_mapping
    build_ios_app(export_method: "ad-hoc") # gym
  end

  desc "Build binary - appstore"
  lane :build_appstore do
    sync_code_signing(type: "appstore") # match
    sign_mapping
    build_ios_app # gym
  end

  desc "Release"
  lane :release do
    build
    upload_to_app_store # deliver
  end
end
